// Package teachingartifact owns immutable, generated teaching code trees.
// It deliberately does not accept a caller-supplied filesystem directory.
package teachingartifact

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const MaxArtifactBytes int64 = 8 << 20

var (
	ErrInvalidToken = errors.New("invalid teaching artifact token")
	ErrUnsafeFile   = errors.New("unsafe teaching artifact file")
	ErrTooLarge     = errors.New("teaching artifact exceeds byte limit")
)

type File struct {
	Path    string
	Content []byte
}

type Artifact struct {
	Token        string
	ArtifactHash string
	ByteSize     int64
	FileCount    int
}

type Store struct {
	rootDir   string
	maxBytes  int64
	readGroup *int
}

// ReaderGroupID is the dedicated read-only group shared by artifact publishers
// and the non-root runner. It grants no access to provider receipts or secrets.
const ReaderGroupID = 20001

// WithReadGroup enables group-readable trees for a trusted cross-process
// publisher. Default stores remain private; readers need a read-only mount.
func (store *Store) WithReadGroup(gid int) *Store {
	store.readGroup = &gid
	return store
}

func NewStore(rootDir string) *Store {
	return NewStoreWithMaxBytes(rootDir, MaxArtifactBytes)
}

func NewStoreWithMaxBytes(rootDir string, maxBytes int64) *Store {
	return &Store{rootDir: strings.TrimSpace(rootDir), maxBytes: maxBytes}
}

// Stage atomically creates a content-addressed tree. The caller supplies
// generated bytes rather than a source directory, closing the path by which a
// checked-out repository could be mistaken for an executable teaching artifact.
func (store *Store) Stage(ctx context.Context, files []File) (Artifact, error) {
	if store == nil {
		return Artifact{}, fmt.Errorf("teaching store is not configured")
	}
	if err := validateArtifactFiles(files, "", store.maxBytes); err != nil {
		return Artifact{}, err
	}
	return store.stage(ctx, files, store.maxBytes)
}

func (store *Store) stage(ctx context.Context, files []File, limit int64) (Artifact, error) {
	if store == nil || strings.TrimSpace(store.rootDir) == "" || store.maxBytes < 1 {
		return Artifact{}, fmt.Errorf("stage teaching artifact: invalid artifact store")
	}
	normalized, byteSize, err := normalizeFiles(files, limit)
	if err != nil {
		return Artifact{}, err
	}
	if err := ctx.Err(); err != nil {
		return Artifact{}, err
	}
	if err := os.MkdirAll(store.rootDir, 0o750); err != nil {
		return Artifact{}, fmt.Errorf("create teaching artifact root: %w", err)
	}
	if store.readGroup != nil {
		if err := setReaderPermission(store.rootDir, true, *store.readGroup); err != nil {
			return Artifact{}, err
		}
	}
	temporary, err := os.MkdirTemp(store.rootDir, ".teaching-artifact-")
	if err != nil {
		return Artifact{}, fmt.Errorf("create teaching artifact workspace: %w", err)
	}
	defer func() { _ = os.RemoveAll(temporary) }()
	for _, file := range normalized {
		if err := ctx.Err(); err != nil {
			return Artifact{}, err
		}
		target := filepath.Join(temporary, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(target), 0o750); err != nil {
			return Artifact{}, fmt.Errorf("create teaching artifact directory: %w", err)
		}
		if err := os.WriteFile(target, file.Content, 0o600); err != nil {
			return Artifact{}, fmt.Errorf("write teaching artifact file: %w", err)
		}
	}
	artifactHash, err := TreeHash(temporary)
	if err != nil {
		return Artifact{}, err
	}
	digest, err := tokenDigest(artifactHash)
	if err != nil {
		return Artifact{}, err
	}
	finalPath := filepath.Join(store.rootDir, digest)
	if err := os.Rename(temporary, finalPath); err != nil && !errors.Is(err, os.ErrExist) {
		return Artifact{}, fmt.Errorf("finalize teaching artifact: %w", err)
	}
	if store.readGroup != nil {
		// Recheck existing bytes before repairing permissions on an idempotent
		// publish. Never change content or grant read access to a mismatched tree.
		if actual, err := TreeHash(finalPath); err != nil || actual != artifactHash {
			return Artifact{}, fmt.Errorf("shared teaching artifact integrity mismatch")
		}
		if err := shareReadTree(finalPath, *store.readGroup); err != nil {
			return Artifact{}, err
		}
	}
	return Artifact{Token: artifactHash, ArtifactHash: artifactHash, ByteSize: byteSize, FileCount: len(normalized)}, nil
}

// Resolve returns a directory only to a trusted in-process adapter. The token
// is content-addressed; no filename, path, URL, or caller-controlled suffix is
// ever joined to the artifact root.
func (store *Store) Resolve(token string) (string, error) {
	return store.ResolveWithGoDependencies(token, "")
}

// ResolveWithGoDependencies requires the hash from the persisted artifact
// manifest before accepting a larger, independently budgeted dependency tree.
func (store *Store) ResolveWithGoDependencies(token, dependencyManifestHash string) (string, error) {
	if store == nil || strings.TrimSpace(store.rootDir) == "" {
		return "", fmt.Errorf("resolve teaching artifact: invalid artifact store")
	}
	digest, err := tokenDigest(token)
	if err != nil {
		return "", err
	}
	root, err := filepath.Abs(store.rootDir)
	if err != nil {
		return "", err
	}
	resolvedRoot, err := filepath.EvalSymlinks(root)
	if err != nil {
		return "", fmt.Errorf("resolve teaching artifact root: %w", err)
	}
	resolvedArtifact, err := filepath.EvalSymlinks(filepath.Join(resolvedRoot, digest))
	if err != nil {
		return "", fmt.Errorf("resolve teaching artifact: %w", err)
	}
	relative, err := filepath.Rel(resolvedRoot, resolvedArtifact)
	if err != nil || relative == "." || relative == ".." || strings.HasPrefix(relative, ".."+string(filepath.Separator)) {
		return "", ErrInvalidToken
	}
	info, err := os.Stat(resolvedArtifact)
	if err != nil || !info.IsDir() {
		return "", ErrInvalidToken
	}
	limit := store.maxBytes
	if dependencyManifestHash != "" {
		limit = combinedArtifactLimit
	}
	files, err := readBoundedArtifactFiles(context.Background(), resolvedArtifact, limit)
	if err != nil {
		return "", err
	}
	if err := validateArtifactFiles(files, dependencyManifestHash, store.maxBytes); err != nil {
		return "", err
	}
	actualHash, err := TreeHash(resolvedArtifact)
	if err != nil {
		return "", err
	}
	if actualHash != token {
		return "", fmt.Errorf("teaching artifact hash mismatch")
	}
	return resolvedArtifact, nil
}

// TreeHash calculates a deterministic hash for a regular-file-only artifact
// tree. Directories and relative paths are part of the hash, preventing a
// different layout from masquerading as an equivalent teaching artifact.
func TreeHash(root string) (string, error) {
	if strings.TrimSpace(root) == "" || !filepath.IsAbs(root) || filepath.Clean(root) == string(filepath.Separator) {
		return "", fmt.Errorf("%w: root", ErrUnsafeFile)
	}
	rootInfo, err := os.Stat(root)
	if err != nil || !rootInfo.IsDir() {
		return "", fmt.Errorf("%w: root", ErrUnsafeFile)
	}
	hasher := sha256.New()
	fileCount := 0
	entries := 0
	var totalBytes int64
	err = filepath.Walk(root, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		entries++
		if entries > combinedArtifactFiles*2 {
			return ErrTooLarge
		}
		relative, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		if relative == "." {
			return nil
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("%w: symlink %s", ErrUnsafeFile, relative)
		}
		if info.IsDir() {
			_, _ = io.WriteString(hasher, "dir\x00"+filepath.ToSlash(relative)+"\x00")
			return nil
		}
		if !info.Mode().IsRegular() {
			return fmt.Errorf("%w: unsupported file %s", ErrUnsafeFile, relative)
		}
		if fileCount >= combinedArtifactFiles {
			return ErrTooLarge
		}
		input, err := os.Open(path) //nolint:gosec // path comes from filepath.Walk under a validated root.
		if err != nil {
			return err
		}
		_, _ = io.WriteString(hasher, "file\x00"+filepath.ToSlash(relative)+"\x00")
		copied, copyErr := io.Copy(hasher, io.LimitReader(input, combinedArtifactLimit-totalBytes+1))
		closeErr := input.Close()
		totalBytes += copied
		if totalBytes > combinedArtifactLimit {
			return ErrTooLarge
		}
		if copyErr != nil {
			return copyErr
		}
		if closeErr != nil {
			return closeErr
		}
		_, _ = io.WriteString(hasher, "\x00")
		fileCount++
		return nil
	})
	if err != nil {
		return "", fmt.Errorf("hash teaching artifact tree: %w", err)
	}
	if fileCount == 0 {
		return "", fmt.Errorf("%w: no files", ErrUnsafeFile)
	}
	return "sha256:" + hex.EncodeToString(hasher.Sum(nil)), nil
}

func normalizeFiles(files []File, maxBytes int64) ([]File, int64, error) {
	if len(files) == 0 {
		return nil, 0, fmt.Errorf("%w: no files", ErrUnsafeFile)
	}
	normalized := append([]File(nil), files...)
	sort.Slice(normalized, func(left, right int) bool { return normalized[left].Path < normalized[right].Path })
	seen := make(map[string]struct{}, len(normalized))
	var byteSize int64
	for index := range normalized {
		path := strings.TrimSpace(normalized[index].Path)
		cleaned := filepath.ToSlash(filepath.Clean(filepath.FromSlash(path)))
		if path == "" || filepath.IsAbs(path) || cleaned == "." || cleaned == ".." || strings.HasPrefix(cleaned, "../") || cleaned != path {
			return nil, 0, fmt.Errorf("%w: %q", ErrUnsafeFile, normalized[index].Path)
		}
		if _, exists := seen[cleaned]; exists {
			return nil, 0, fmt.Errorf("%w: duplicate %q", ErrUnsafeFile, cleaned)
		}
		seen[cleaned] = struct{}{}
		normalized[index].Path = cleaned
		byteSize += int64(len(normalized[index].Content))
		if byteSize > maxBytes {
			return nil, 0, ErrTooLarge
		}
	}
	return normalized, byteSize, nil
}

func tokenDigest(token string) (string, error) {
	token = strings.TrimSpace(token)
	if !strings.HasPrefix(token, "sha256:") {
		return "", ErrInvalidToken
	}
	digest := strings.TrimPrefix(token, "sha256:")
	if len(digest) != sha256.Size*2 {
		return "", ErrInvalidToken
	}
	if _, err := hex.DecodeString(digest); err != nil {
		return "", ErrInvalidToken
	}
	return strings.ToLower(digest), nil
}
