//go:build integration

package integration_test

import (
	"archive/zip"
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/stretchr/testify/require"

	exportartifact "inkwords-backend/services/export-service/infra/artifact"
	stream "inkwords-backend/services/llm-stream/domain/stream"
	"inkwords-backend/shared/platform/obsidian"
	parser "inkwords-backend/shared/platform/parser"
	sharedmq "inkwords-backend/shared/platform/rabbitmq"
)

// TestAsyncPipelineContracts exercises the stable boundaries shared by the
// parser, generation worker, core task persistence, and export worker. It is
// intentionally self-contained so CI can run it without databases or secrets.
func TestAsyncPipelineContracts(t *testing.T) {
	t.Parallel()

	archive := buildZIP(t, map[string]string{
		"docs/lesson.md":  "# Go queues\n\nAck only after persistence.\n",
		"src/worker.go":   "package worker\n",
		"copy/worker.go":  "package worker\n",
		"assets/logo.png": "not parsed",
	})

	parsed, err := parser.NewArchiveParser(parser.NewDocParser()).ParseArchive(bytes.NewReader(archive), "course.zip")
	require.NoError(t, err)
	require.Contains(t, parsed.SourceContent, "# Go queues")
	require.Contains(t, parsed.SourceContent, "package worker")
	require.Equal(t, 4, parsed.ArchiveSummary.TotalFiles)
	require.Equal(t, 2, parsed.ArchiveSummary.KeptFiles)
	require.Equal(t, 1, parsed.ArchiveSummary.DuplicateFiles)
	require.Equal(t, 1, parsed.ArchiveSummary.IgnoredFiles)

	taskID := uuid.MustParse("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
	userID := uuid.MustParse("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
	payload, err := json.Marshal(stream.GenerateRequest{
		SourceType:    "file",
		SourceContent: parsed.SourceContent,
		ScenarioMode:  "ebook_interpretation",
	})
	require.NoError(t, err)

	wire, err := json.Marshal(sharedmq.GenerationRequestedMessage{
		TaskID: taskID, Kind: "generate_single", UserID: userID, Payload: payload,
	})
	require.NoError(t, err)
	var received sharedmq.GenerationRequestedMessage
	require.NoError(t, json.Unmarshal(wire, &received))
	require.Equal(t, "generation.requested", received.RoutingKey())
	require.Equal(t, taskID, received.TaskID)
	require.Equal(t, userID, received.UserID)

	resultJSON, err := stream.BuildGenerateSingleTaskResult(stream.GenerateSingleTaskResultInput{
		BlogID: "cccccccc-cccc-cccc-cccc-cccccccccccc", Title: "Queue safety",
		Content: "# Queue safety", SourceType: "file", WordCount: 2,
		TechStacks: []string{"Go", "RabbitMQ"}, EstimatedTokens: 12,
	})
	require.NoError(t, err)
	var result stream.TaskResultEnvelope
	require.NoError(t, json.Unmarshal(resultJSON, &result))
	require.Equal(t, 1, result.ResultVersion)
	require.Equal(t, "generation", result.TaskType)
	require.Equal(t, "generate_single", result.TaskSubtype)
	require.Equal(t, "task_only", result.PersistenceMode)
	require.Equal(t, "succeeded", result.FinalStatus)
	require.Equal(t, 12, result.Usage.EstimatedTokens)
	require.Equal(t, "cccccccc-cccc-cccc-cccc-cccccccccccc", result.Payload["blog_id"])
}

func TestExportArtifactContract(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	source := filepath.Join(root, "rendered.pdf")
	pdf := []byte("%PDF-1.4\n% deterministic fixture\n%%EOF\n")
	require.NoError(t, os.WriteFile(source, pdf, 0o600))

	now := time.Date(2026, 7, 2, 12, 0, 0, 0, time.UTC)
	store := exportartifact.NewStoreWithClock(filepath.Join(root, "artifacts"), 15*time.Minute, func() time.Time { return now })
	result, err := store.Save(uuid.MustParse("dddddddd-dddd-dddd-dddd-dddddddddddd"), source, "series.pdf")
	require.NoError(t, err)
	require.Equal(t, "application/pdf", result.ContentType)
	require.Equal(t, "series.pdf", result.Filename)
	require.Equal(t, now.Add(15*time.Minute), result.ExpiresAt)
	require.NoFileExists(t, source)

	stored, err := os.ReadFile(store.PathForToken(result.FileToken)) //nolint:gosec -- path is generated by the store.
	require.NoError(t, err)
	require.True(t, bytes.HasPrefix(stored, []byte("%PDF-")), "download artifact must retain the PDF magic header")
}

func TestObsidianAdapterRoundTripContract(t *testing.T) {
	t.Parallel()

	const notePath = "/vault/wiki/e2e/run-123/note.md"
	var note []byte
	client := &http.Client{Transport: roundTripFunc(func(r *http.Request) (*http.Response, error) {
		require.Equal(t, "Bearer test-token", r.Header.Get("Authorization"))
		require.Equal(t, notePath, r.URL.Path)
		response := &http.Response{StatusCode: http.StatusOK, Header: make(http.Header), Body: http.NoBody}
		switch r.Method {
		case http.MethodPut:
			var err error
			note, err = io.ReadAll(r.Body)
			require.NoError(t, err)
			response.StatusCode = http.StatusNoContent
		case http.MethodGet:
			response.Header.Set("Content-Type", "text/markdown")
			response.Body = io.NopCloser(bytes.NewReader(note))
		default:
			response.StatusCode = http.StatusMethodNotAllowed
		}
		return response, nil
	})}

	baseURL, err := url.Parse("https://obsidian.test")
	require.NoError(t, err)
	store := obsidian.NewRestAPIStore(baseURL, "test-token", client)
	want := []byte("---\ntitle: Contract note\n---\n\n# Contract note\n")
	require.NoError(t, store.Put(context.Background(), "wiki/e2e/run-123/note.md", "text/markdown", want))
	got, err := store.Read(context.Background(), "wiki/e2e/run-123/note.md")
	require.NoError(t, err)
	require.Equal(t, want, got)
}

type roundTripFunc func(*http.Request) (*http.Response, error)

func (f roundTripFunc) RoundTrip(request *http.Request) (*http.Response, error) {
	return f(request)
}

func TestArchiveParserRejectsTraversalAtIntegrationBoundary(t *testing.T) {
	t.Parallel()

	archive := buildZIP(t, map[string]string{"../outside.md": "must not escape"})
	_, err := parser.NewArchiveParser(parser.NewDocParser()).ParseArchive(bytes.NewReader(archive), "unsafe.zip")
	require.ErrorContains(t, err, "非法压缩包路径")
}

func buildZIP(t *testing.T, files map[string]string) []byte {
	t.Helper()
	var buf bytes.Buffer
	writer := zip.NewWriter(&buf)
	for name, content := range files {
		entry, err := writer.Create(name)
		require.NoError(t, err)
		_, err = io.WriteString(entry, content)
		require.NoError(t, err)
	}
	require.NoError(t, writer.Close())
	return buf.Bytes()
}
