const pathSegment = (value: string) => encodeURIComponent(value)

/**
 * Browser code only uses same-origin paths. Service ownership is recorded here
 * so domain clients do not need to know container names or internal ports.
 */
export const apiRoutes = {
  coreApi: {
    blogs: {
      collection: '/api/v1/blogs',
      draft: '/api/v1/blogs/draft',
      byId: (blogId: string) => `/api/v1/blogs/${pathSegment(blogId)}`,
    },
    tasks: {
      generation: '/api/v1/tasks/generation',
      parse: '/api/v1/tasks/parse',
      export: '/api/v1/tasks/export',
      byId: (taskId: string) => `/api/v1/tasks/${pathSegment(taskId)}`,
      cancel: (taskId: string) => `/api/v1/tasks/${pathSegment(taskId)}/cancel`,
      retry: (taskId: string) => `/api/v1/tasks/${pathSegment(taskId)}/retry`,
      stream: (taskId: string) => `/api/v1/tasks/${pathSegment(taskId)}/stream`,
      download: (taskId: string) => `/api/v1/tasks/${pathSegment(taskId)}/download`,
    },
    textbookProjects: {
      collection: '/api/v1/textbook-projects',
      dependencyProjection: (chapterId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/dependency-projection`,
	  task: (taskId: string) => `/api/v1/textbook-projects/tasks/${pathSegment(taskId)}`,
	  retryTask: (taskId: string) => `/api/v1/textbook-projects/tasks/${pathSegment(taskId)}/retry`,
      byId: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}`,
      workspace: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/workspace`,
      progress: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/progress`,
      sourceLibrary: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/source-library`,
      sourceEvidence: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/source-evidence`,
		sourceRetrieval: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/source-retrieval`,
      sources: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/sources`,
		sourceImports: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/source-imports`,
		officialWebImports: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/official-web-imports`,
		loadGinFixture: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/load-gin-fixture`,
      chapters: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/chapters`,
      bookContracts: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/book-contracts`,
      styleSheets: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/style-sheets`,
      blueprints: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/blueprints`,
	  bookBuilds: (projectId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/book-builds`,
	  editorialWorkspace: (buildId: string) => `/api/v1/textbook-projects/book-builds/${pathSegment(buildId)}/editorial`,
	  publicationRights: (buildId: string) => `/api/v1/textbook-projects/book-builds/${pathSegment(buildId)}/rights`,
	  rightsAmendments: (buildId: string) => `/api/v1/textbook-projects/book-builds/${pathSegment(buildId)}/rights-amendments`,
	  publicationReviews: (buildId: string) => `/api/v1/textbook-projects/book-builds/${pathSegment(buildId)}/reviews`,
	  delegatedPublicationReviews: (buildId: string) => `/api/v1/textbook-projects/book-builds/${pathSegment(buildId)}/delegated-reviews`,
	  publicationCandidate: (buildId: string) => `/api/v1/textbook-projects/book-builds/${pathSegment(buildId)}/publication-candidate`,
      approveBookContract: (projectId: string, revisionId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/book-contracts/${pathSegment(revisionId)}/approve`,
      approveStyleSheet: (projectId: string, revisionId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/style-sheets/${pathSegment(revisionId)}/approve`,
      approveBlueprint: (projectId: string, revisionId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/blueprints/${pathSegment(revisionId)}/approve`,
      chapterWorkspace: (chapterId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/workspace`,
      artifactVerification: (chapterId: string, artifactId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/code-artifacts/${pathSegment(artifactId)}/verify`,
      chapterLock: (chapterId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/lock`,
      revisions: (chapterId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/revisions`,
      applyCandidate: (chapterId: string, revisionId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/revisions/${pathSegment(revisionId)}/apply`,
		rejectCandidate: (chapterId: string, revisionId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/revisions/${pathSegment(revisionId)}/reject`,
		generationPreflight: (projectId: string, chapterId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/chapters/${pathSegment(chapterId)}/generation-preflight`,
		generateSample: (projectId: string, chapterId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/chapters/${pathSegment(chapterId)}/generate-sample`,
		correctSample: (projectId: string, chapterId: string) => `/api/v1/textbook-projects/${pathSegment(projectId)}/chapters/${pathSegment(chapterId)}/correct-sample`,
		uploadVisualAsset: (chapterId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/visual-assets`,
		chapterProjections: (chapterId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/projections`,
    },
  },
  llmStream: {
    scan: '/api/v1/stream/scan',
    analyze: '/api/v1/stream/analyze',
    generate: '/api/v1/stream/generate',
	providerConnectionTest: '/api/v1/stream/provider-connection-test',
    continueBlog: (blogId: string) => `/api/v1/blogs/${pathSegment(blogId)}/continue`,
    polishBlog: (blogId: string) => `/api/v1/blogs/${pathSegment(blogId)}/polish`,
  },
  parserService: {
    parseProject: '/api/v1/project/parse',
  },
  exportService: {
    seriesZip: (blogId: string) => `/api/v1/blogs/${pathSegment(blogId)}/export`,
    seriesPdf: (blogId: string) => `/api/v1/blogs/${pathSegment(blogId)}/export/pdf`,
    blogToObsidian: (blogId: string) => `/api/v1/blogs/${pathSegment(blogId)}/export/obsidian`,
    seriesToObsidian: (blogId: string) => `/api/v1/blogs/${pathSegment(blogId)}/export/obsidian/series`,
		textbookChapterMarkdown: (chapterId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/export/markdown`,
		textbookChapterZip: (chapterId: string) => `/api/v1/textbook-projects/chapters/${pathSegment(chapterId)}/export/zip`,
		textbookBookBuildMarkdown: (buildId: string) => `/api/v1/textbook-projects/book-builds/${pathSegment(buildId)}/export/markdown`,
		textbookBookBuildDOCX: (buildId: string) => `/api/v1/textbook-projects/book-builds/${pathSegment(buildId)}/export/docx`,
		textbookBookBuildPDF: (buildId: string) => `/api/v1/textbook-projects/book-builds/${pathSegment(buildId)}/export/pdf`,
		textbookBookBuildReviewBundle: (buildId: string) => `/api/v1/textbook-projects/book-builds/${pathSegment(buildId)}/export/review-bundle`,
  },
  reviewService: {
    today: '/api/v1/review/today',
    pick: '/api/v1/review/pick',
    notes: '/api/v1/review/notes',
    history: '/api/v1/review/history',
    sessions: '/api/v1/review/sessions',
    session: (sessionId: string) => `/api/v1/review/sessions/${pathSegment(sessionId)}`,
    readingComplete: (sessionId: string) => `/api/v1/review/sessions/${pathSegment(sessionId)}/reading-complete`,
    respond: (sessionId: string) => `/api/v1/review/sessions/${pathSegment(sessionId)}/respond`,
    hint: (sessionId: string) => `/api/v1/review/sessions/${pathSegment(sessionId)}/hint`,
    finish: (sessionId: string) => `/api/v1/review/sessions/${pathSegment(sessionId)}/finish`,
    masteryDue: '/api/v1/mastery/due',
    masteryObjectives: '/api/v1/mastery/objectives',
    masteryObjective: (objectiveId: string) => `/api/v1/mastery/objectives/${pathSegment(objectiveId)}`,
    masteryAttempts: (objectiveId: string) => `/api/v1/mastery/objectives/${pathSegment(objectiveId)}/attempts`,
    masterySessions: (objectiveId: string) => `/api/v1/mastery/objectives/${pathSegment(objectiveId)}/practice-sessions`,
    masteryAssessmentAttempt: (objectiveId: string, attemptId: string) => `/api/v1/mastery/objectives/${pathSegment(objectiveId)}/attempts/${pathSegment(attemptId)}`,
    masteryAssessmentJob: (objectiveId: string, jobId: string) => `/api/v1/mastery/objectives/${pathSegment(objectiveId)}/assessments/${pathSegment(jobId)}`,
    masterySession: (objectiveId: string, sessionId: string) => `/api/v1/mastery/objectives/${pathSegment(objectiveId)}/practice-sessions/${pathSegment(sessionId)}`,
  },
} as const
