package bookrender

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/xml"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/chromedp/cdproto/css"
	exportdomain "inkwords-backend/services/export-service/domain/export"
)

const reviewedFontProfile = "inkwords.pdf-font-source-set.v1"

// These exact unmodified files were separately reviewed for document embedding.
// A package upgrade must fail this profile until its new bytes are reviewed.
var reviewedFontFiles = []struct{ path, hash string }{
	{"/usr/share/fonts/freefont/FreeMono.otf", "daf720e115bc462f721cdf3065697b75fea033bf46d4598d3a727fce4b036032"},
	{"/usr/share/fonts/freefont/FreeSans.otf", "d3e9138ccf76ef516cc6af867e4e7ed8776331947235824f924c5886186b0c80"},
	{"/usr/share/fonts/noto/NotoSansCJK-Bold.ttc", "faa5f3656a78b2e2d450d27fe8382c778bc2b6bb5ea29c986664a6a435056ceb"},
	{"/usr/share/fonts/noto/NotoSansCJK-Regular.ttc", "b76b0433203017ca80401b2ee0dd69350349871c4b19d504c34dbdd80541690a"},
}

var fontRuleFiles = []string{
	"10-hinting-slight.conf", "10-scale-bitmap-fonts.conf", "10-sub-pixel-none.conf", "10-yes-antialias.conf",
	"11-lcdfilter-default.conf", "20-unhint-small-vera.conf", "30-metric-aliases.conf", "40-nonlatin.conf",
	"45-generic.conf", "45-latin.conf", "48-spacing.conf", "49-sansserif.conf", "60-generic.conf", "60-latin.conf",
	"65-fonts-persian.conf", "65-nonlatin.conf", "69-unifont.conf", "80-delicious.conf", "90-synthetic.conf",
}

type renderFontProfile struct {
	env        []string
	files      map[string]string
	charsets   map[string]string
	configPath string
	evidence   exportdomain.PDFFontSourceSet
}

func prepareFontProfile(ctx context.Context, directory string) (*renderFontProfile, error) {
	// chromedp merges its environment with the parent's. Reject this optional
	// relocation setting instead of pretending an empty value unsets it.
	if _, inherited := os.LookupEnv("FONTCONFIG_SYSROOT"); inherited {
		return nil, fmt.Errorf("FONTCONFIG_SYSROOT is incompatible with the reviewed font profile")
	}
	// Font bytes remain in the read-only image's deployment font hierarchy.
	fontDir := "/usr/share/fonts/inkwords-reviewed"
	cacheDir := filepath.Join(directory, "font-cache")
	if err := os.Mkdir(cacheDir, 0o700); err != nil {
		return nil, err
	}
	p := &renderFontProfile{files: map[string]string{}, evidence: exportdomain.PDFFontSourceSet{Format: reviewedFontProfile, Scope: "fontconfig_text_and_print_furniture", ConfigurationSources: map[string]string{}}}
	for _, font := range reviewedFontFiles {
		if err := ctx.Err(); err != nil {
			return nil, err
		}
		path := filepath.Join(fontDir, filepath.Base(font.path))
		resolved, err := filepath.EvalSymlinks(path)
		if err != nil || resolved != font.path {
			return nil, fmt.Errorf("reviewed font deployment path changed")
		}
		data, err := readBoundedDeploymentFile(path, 64<<20)
		if err != nil || fmt.Sprintf("%x", sha256.Sum256(data)) != font.hash {
			return nil, fmt.Errorf("reviewed font bytes unavailable or changed: %s", filepath.Base(font.path))
		}
		p.files[path] = "sha256:" + font.hash
		p.evidence.FileHashes = append(p.evidence.FileHashes, "sha256:"+font.hash)
	}
	var config bytes.Buffer
	config.WriteString(`<?xml version="1.0"?><!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd"><fontconfig><reset-dirs/>`)
	// The temporary path is generated by us; XML encoding still handles any
	// special characters in a configured system temporary directory.
	for _, pair := range [][2]string{{"dir", fontDir}, {"cachedir", cacheDir}} {
		fmt.Fprintf(&config, "<%s>", pair[0])
		escapeFontXML(&config, pair[1])
		fmt.Fprintf(&config, "</%s>", pair[0])
	}
	paths := []string{"/etc/fonts/fonts.conf"}
	for _, file := range fontRuleFiles {
		paths = append(paths, filepath.Join("/etc/fonts/conf.d", file))
	}
	for i, path := range paths {
		raw, err := readBoundedDeploymentFile(path, 256<<10)
		if err != nil {
			return nil, fmt.Errorf("font rendering rules unavailable")
		}
		rules, err := extractFontRules(raw, i == 0)
		if err != nil {
			return nil, err
		}
		config.Write(rules)
		p.evidence.ConfigurationSources[path] = fmt.Sprintf("sha256:%x", sha256.Sum256(raw))
	}
	config.WriteString(`<config><rescan><int>0</int></rescan></config></fontconfig>`)
	configPath := filepath.Join(directory, "fonts.conf")
	if err := os.WriteFile(configPath, config.Bytes(), 0o400); err != nil {
		return nil, err
	}
	p.evidence.ConfigurationHash = fmt.Sprintf("sha256:%x", sha256.Sum256(config.Bytes()))
	p.env = fontProfileEnvironment(os.Environ(), configPath)
	p.configPath = configPath
	charset, err := p.fontconfigOutput(ctx, "fc-list", "--format", "%{postscriptname}\t%{charset}\n")
	if err != nil {
		return nil, err
	}
	p.charsets = map[string]string{}
	for _, line := range strings.Split(strings.TrimSpace(string(charset)), "\n") {
		name, ranges, ok := strings.Cut(line, "\t")
		if !ok || name == "" || ranges == "" || p.charsets[name] != "" {
			return nil, fmt.Errorf("ambiguous or incomplete font character inventory")
		}
		p.charsets[name] = ranges
	}
	if err := requireFontCharacters(p.charsets["NotoSansCJKsc-Regular"], "第 0123456789 页 / 共"); err != nil {
		return nil, err
	}
	p.evidence.FooterCharsetStatus = "covered_by_source_set"
	return p, nil
}

func escapeFontXML(w io.Writer, value string) {
	_ = xml.EscapeText(w, []byte(value))
}

func readBoundedDeploymentFile(path string, limit int64) ([]byte, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	info, err := f.Stat()
	if err != nil || !info.Mode().IsRegular() || info.Size() > limit {
		return nil, fmt.Errorf("font profile file outside size/type budget")
	}
	data, err := io.ReadAll(io.LimitReader(f, limit+1))
	if err != nil || int64(len(data)) != info.Size() {
		return nil, fmt.Errorf("font profile file changed during snapshot")
	}
	return data, nil
}

func (p *renderFontProfile) fontconfigOutput(ctx context.Context, command string, args ...string) ([]byte, error) {
	ctx, cancel := context.WithTimeout(ctx, 3*time.Second)
	defer cancel()
	cmd := exec.CommandContext(ctx, command, args...)
	cmd.Env = p.env
	var output fontListOutput
	var diagnostics boundedLog
	cmd.Stdout, cmd.Stderr = &output, &diagnostics
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("font profile inventory unavailable")
	}
	if output.Len() == 0 || strings.Contains(diagnostics.String(), "Fontconfig error:") {
		return nil, fmt.Errorf("font profile produced no usable inventory: %s", diagnostics.String())
	}
	return output.Bytes(), nil
}

func (p *renderFontProfile) inventory(ctx context.Context) ([]exportdomain.FontFileEvidence, error) {
	config, err := readBoundedDeploymentFile(p.configPath, 1<<20)
	if err != nil || fmt.Sprintf("sha256:%x", sha256.Sum256(config)) != p.evidence.ConfigurationHash {
		return nil, fmt.Errorf("font profile configuration changed")
	}
	raw, err := p.fontconfigOutput(ctx, "fc-list", "--format", fontListFormat)
	if err != nil {
		return nil, err
	}
	seen := map[string]bool{}
	faces, err := parseFontInventory(string(raw), func(path string) (string, error) {
		expected, ok := p.files[path]
		if !ok {
			return "", fmt.Errorf("font outside closed profile")
		}
		data, err := readBoundedDeploymentFile(path, 64<<20)
		if err != nil || fmt.Sprintf("sha256:%x", sha256.Sum256(data)) != expected {
			return "", fmt.Errorf("font profile snapshot changed")
		}
		seen[path] = true
		return expected, nil
	})
	if err != nil || len(seen) != len(p.files) {
		return nil, fmt.Errorf("font profile inventory differs from declared source set")
	}
	return faces, nil
}

func (p *renderFontProfile) validateObservedCharacters(fonts []*css.PlatformFontUsage, text string) error {
	var ranges strings.Builder
	for _, font := range fonts {
		if font.GlyphCount <= 0 {
			continue
		}
		charset, known := p.charsets[font.PostScriptName]
		if font.IsCustomFont || !known {
			return fmt.Errorf("observed font is outside the reviewed character inventory")
		}
		ranges.WriteString(charset)
		ranges.WriteByte(' ')
	}
	return requireFontCharacters(ranges.String(), text)
}
